name: scryfall_api
description: A wrapper of the Scryfall API for the Dart programming language.
version: 0.1.0
homepage: https://github.com/aroningruber/scryfall_api

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  http: ^0.13.4
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
  mocktail: ^0.2.0
  test: ^1.20.1
  lints: ^1.0.1
